name: kat
description: A simple utility that reads files sequentially, writing them to standard output.
version: 0.1.101
homepage: https://github.com/tonytins/kat

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  fake_async: ^1.3.0

dependencies:
  args: ^2.3.1
